import { useEffect, useRef, useState, type FormEvent, type KeyboardEvent as ReactKeyboardEvent } from "react";
import { shouldDismissDialog, useProxyRouting, wrappedDialogFocusIndex, type DefaultTarget, type Matcher, type RouteSnapshot, type RouteTarget } from "../../lib/proxy-routing";

type Draft = { name: string; enabled: boolean; matcherType: Matcher["type"]; values: string; target: string };
const blank = (): Draft => ({ name: "", enabled: true, matcherType: "domain", values: "", target: "direct" });
const safeText = (value: string, maximum: number) => Array.from(value).length <= maximum && !/[\u0000-\u001f\u007f]/.test(value);
const targetValue = (target: DefaultTarget | RouteTarget) => target.type === "pool" ? `pool:${target.poolId}` : target.type;
const decodeDefaultTarget = (value: string): DefaultTarget => value.startsWith("pool:") ? { type: "pool", poolId: value.slice(5) } : { type: value as "followActiveSubscription" | "direct" | "block" };
const decodeRouteTarget = (value: string): RouteTarget => value.startsWith("pool:") ? { type: "pool", poolId: value.slice(5) } : { type: value as "direct" | "block" };

export function RoutingPage({ active }: { active: boolean }) {
  const { snapshot, loading, error, pending, notice, refresh, mutate, dismissNotice } = useProxyRouting();
  const operationBusy = pending || snapshot?.applyState.type === "applying" || snapshot?.applyState.type === "applyUnknown";
  const [dialogRoute, setDialogRoute] = useState<RouteSnapshot | "new" | null>(null); const [draft, setDraft] = useState(blank); const [formError, setFormError] = useState<string | null>(null); const triggerRef = useRef<HTMLElement | null>(null);
  useEffect(() => { if (active) void refresh(); }, [active, refresh]);
  const canApply = snapshot?.applyState.type === "savedPendingApply" || snapshot?.applyState.type === "savedApplyFailed";
  function open(route: RouteSnapshot | "new", trigger?: HTMLElement | null) { triggerRef.current = trigger ?? (document.activeElement instanceof HTMLElement ? document.activeElement : null); setDialogRoute(route); setFormError(null); if (route === "new") setDraft(blank()); else setDraft({ name: route.name, enabled: route.enabled, matcherType: route.matcher.type, values: route.matcher.values.join(", "), target: targetValue(route.target) }); }
  function close() { if (pending) return; setDialogRoute(null); queueMicrotask(() => triggerRef.current?.focus()); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!snapshot || pending) return; const name = draft.name.trim(); const raw = draft.values.split(",").map((item) => item.trim()).filter(Boolean); if (!name || !safeText(name, 80)) { setFormError("名称需要 1–80 个无控制字符的文本"); return; } if (!raw.length || raw.length > 500 || new Set(raw).size !== raw.length) { setFormError("需要填写 1–500 个不重复匹配值"); return; } if (draft.matcherType !== "port" && raw.some((value) => !safeText(value, 255))) { setFormError("匹配值不能超过 255 个字符或包含控制字符"); return; } let matcher: Matcher; if (draft.matcherType === "port") { const ports = raw.map(Number); if (ports.some((port) => !Number.isInteger(port) || port < 1 || port > 65535)) { setFormError("端口必须在 1–65535 之间"); return; } matcher = { type: "port", values: ports }; } else if (draft.matcherType === "protocol") { if (raw.some((value) => value !== "tcp" && value !== "udp")) { setFormError("协议只允许 tcp 或 udp"); return; } matcher = { type: "protocol", values: raw as ("tcp" | "udp")[] }; } else matcher = { type: draft.matcherType, values: raw };
    const target = decodeRouteTarget(draft.target); const result = await mutate(dialogRoute === "new" ? { type: "createRoute", name, enabled: draft.enabled, matcher, target, insertAt: snapshot.routes.length } : { type: "updateRoute", id: dialogRoute!.id, name, enabled: draft.enabled, matcher, target }); if (result?.status === "ok") close(); }
  async function move(index: number, delta: number) { if (!snapshot) return; const next = snapshot.routes.map((route) => route.id); const target = index + delta; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; await mutate({ type: "reorderRoutes", routeIds: next }); }
  return <main className="home-content proxy-routing-page" id="page-routing" hidden={!active} aria-labelledby="page-routing-title">
    <header className="home-header"><h1 id="page-routing-title">分流</h1><div className="proxy-header-actions"><button className="primary-button" type="button" disabled={operationBusy || (snapshot?.routes.length ?? 0) >= 500} onClick={(event) => open("new", event.currentTarget)}>新建规则</button><button className="secondary-button" type="button" disabled={operationBusy || !canApply} onClick={() => void mutate({ type: "applyConfiguration" })}>{snapshot?.applyState.type === "applying" ? "应用中…" : "应用"}</button></div></header>
    <div className="page-scroll proxy-routing-scroll">
      {loading && snapshot === null ? <RoutingState text="正在读取分流配置…" /> : error ? <RoutingState text={error === "busy" ? "配置正在使用中" : "分流配置不可用"} action={() => void refresh()} /> : snapshot ? <>
        <section className="default-target surface-row"><div><strong>默认出口</strong><small>未命中任何分流规则时使用</small></div><select aria-label="默认出口" disabled={operationBusy} value={targetValue(snapshot.defaultTarget)} onChange={(event) => void mutate({ type: "setDefaultTarget", target: decodeDefaultTarget(event.target.value) })}><option value="followActiveSubscription">跟随当前订阅</option><option value="direct">直连</option><option value="block">阻止</option>{snapshot.pools.map((pool) => <option key={pool.id} value={`pool:${pool.id}`} disabled={!pool.enabled}>{pool.name}{pool.enabled ? "" : "（停用）"}</option>)}</select></section>
        {snapshot.routes.length === 0 ? <RoutingState text="暂无分流规则，所有流量使用默认出口" /> : <section className="route-list" aria-label="分流规则列表">{snapshot.routes.map((route, index) => <article className={`route-row ${!route.enabled ? "is-disabled" : ""}`} key={route.id}><div className="route-priority"><button className="icon-button" type="button" aria-label={`上移 ${route.name}`} disabled={operationBusy || index === 0} onClick={() => void move(index, -1)}>↑</button><button className="icon-button" type="button" aria-label={`下移 ${route.name}`} disabled={operationBusy || index === snapshot.routes.length - 1} onClick={() => void move(index, 1)}>↓</button></div><div className="route-copy"><strong>{route.name}</strong><small>{matcherLabel(route.matcher)} → {routeTargetLabel(route.target, snapshot.pools)}</small></div><span className="route-enabled">{route.enabled ? "启用" : "停用"}</span><button className="icon-button" type="button" aria-label={`编辑 ${route.name}`} disabled={operationBusy} onClick={(event) => open(route, event.currentTarget)}>•••</button><button className="icon-button danger-icon" type="button" aria-label={`删除 ${route.name}`} disabled={operationBusy} onClick={() => void mutate({ type: "deleteRoute", id: route.id })}>×</button></article>)}</section>}
      </> : null}
    </div>
    {notice ? <div className={`proxy-routing-notice notice-${notice.kind}`} role={notice.kind === "error" ? "alert" : "status"}><span>{notice.message}</span><button type="button" onClick={dismissNotice}>关闭</button></div> : null}
    {dialogRoute && snapshot ? <RouteDialog title={dialogRoute === "new" ? "新建分流规则" : "编辑分流规则"} draft={draft} setDraft={setDraft} pools={snapshot.pools} error={formError} busy={operationBusy} onClose={close} onSubmit={submit} /> : null}
  </main>;
}

function RoutingState({ text, action }: { text: string; action?: () => void }) { return <div className="proxy-routing-state" role="status"><p>{text}</p>{action ? <button className="secondary-button" type="button" onClick={action}>重试</button> : null}</div>; }
function matcherLabel(matcher: Matcher) { const names: Record<Matcher["type"], string> = { domain: "域名", domainSuffix: "域名后缀", application: "应用", ipCidr: "IP 网段", port: "端口", protocol: "协议" }; return `${names[matcher.type]} · ${matcher.values.join(", ")}`; }
function routeTargetLabel(target: RouteTarget, pools: { id: string; name: string }[]) { return target.type === "direct" ? "直连" : target.type === "block" ? "阻止" : pools.find((pool) => pool.id === target.poolId)?.name ?? "未知出口组"; }
function trapTab(event: ReactKeyboardEvent, root: HTMLElement | null) { if (event.key !== "Tab" || !root) return; const controls = Array.from(root.querySelectorAll<HTMLElement>("button:not(:disabled), input:not(:disabled), select:not(:disabled), textarea:not(:disabled), [tabindex]:not([tabindex='-1'])")); const target = wrappedDialogFocusIndex(controls.indexOf(document.activeElement as HTMLElement), controls.length, event.shiftKey); if (target !== null) { event.preventDefault(); controls[target]?.focus(); } }
function RouteDialog({ title, draft, setDraft, pools, error, busy, onClose, onSubmit }: { title: string; draft: Draft; setDraft(value: Draft): void; pools: { id: string; name: string; enabled: boolean }[]; error: string | null; busy: boolean; onClose(): void; onSubmit(event: FormEvent): void }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { ref.current?.querySelector<HTMLElement>("input, button")?.focus(); }, []);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (shouldDismissDialog(event.key, busy)) onClose(); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [busy, onClose]);
  return <div className="dialog-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="proxy-routing-dialog" ref={ref} role="dialog" aria-modal="true" aria-labelledby="route-dialog-title" tabIndex={-1} onKeyDown={(event) => trapTab(event, ref.current)}><form onSubmit={onSubmit}><header><h2 id="route-dialog-title">{title}</h2></header><div className="dialog-fields"><label>名称<input maxLength={80} value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label className="checkbox-line"><input type="checkbox" checked={draft.enabled} onChange={(event) => setDraft({ ...draft, enabled: event.target.checked })} />启用规则</label><div className="dialog-grid"><label>匹配类型<select value={draft.matcherType} onChange={(event) => setDraft({ ...draft, matcherType: event.target.value as Matcher["type"] })}><option value="domain">域名</option><option value="domainSuffix">域名后缀</option><option value="application">应用</option><option value="ipCidr">IP 网段</option><option value="port">端口</option><option value="protocol">协议</option></select></label><label>目标出口<select value={draft.target} onChange={(event) => setDraft({ ...draft, target: event.target.value })}><option value="direct">直连</option><option value="block">阻止</option>{pools.map((pool) => <option key={pool.id} value={`pool:${pool.id}`} disabled={!pool.enabled}>{pool.name}{pool.enabled ? "" : "（停用）"}</option>)}</select></label></div><label>匹配值（逗号分隔）<textarea rows={4} value={draft.values} onChange={(event) => setDraft({ ...draft, values: event.target.value })} /></label>{error ? <p className="dialog-error" role="alert">{error}</p> : null}</div><footer><button className="secondary-button" type="button" disabled={busy} onClick={onClose}>取消</button><button className="primary-button" type="submit" disabled={busy}>{busy ? "保存中…" : "保存"}</button></footer></form></div></div>;
}
