import { useEffect, useRef, useState } from "react";
import { ArrowPathIcon, ChevronDownIcon, EyeIcon, PencilSquareIcon, PlusIcon, TrashIcon, XMarkIcon } from "@heroicons/react/24/outline";
import { api } from "../../api/client";
import type { DnsFilterConfig, DnsFilterList, DnsFilterStatus, DnsPreview } from "../../api/types";
import { IconButton, Modal, Tooltip } from "../../components/shared";
import { SelectControl, SwitchControl } from "../../ui/controls";
import { DnsPagination } from "./DnsQueryRecords";
import { DNS_TEXT as T } from "./DnsSettings.messages";
import { dnsError, dnsMessage, parseAllowDomains } from "./DnsSettings.helpers";

function FilterPreview({ list, onClose, onToast }: { list: DnsFilterList; onClose: () => void; onToast: (message: string) => void }) {
  const [search, setSearch] = useState(""), [action, setAction] = useState("all"), [query, setQuery] = useState({ search: "", action: "all" }), [page, setPage] = useState(1), [size, setSize] = useState(20), [data, setData] = useState<DnsPreview | null>(null), [busy, setBusy] = useState(true), [error, setError] = useState("");
  const notify = useRef(onToast); notify.current = onToast;
  useEffect(() => { const timer = window.setTimeout(() => { setQuery({ search, action }); setPage(1); }, 250); return () => window.clearTimeout(timer); }, [search, action]);
  useEffect(() => { let active = true; setBusy(true); setError(""); if (query.search !== search || query.action !== action) return; void api.dnsPreview(list.url, query.search.trim(), query.action, page, size).then(next => { if (active) setData(next); }, reason => { if (active) { setData(null); setError(dnsError(reason)); notify.current(dnsError(reason)); } }).finally(() => { if (active) setBusy(false); }); return () => { active = false; }; }, [list.url, query, page, size, search, action]);
  return <Modal title={T.dfPreviewTitle} className="dns-dialog dns-preview-dialog routing-dialog" onClose={onClose}><div><strong>{list.name}</strong><p className="dns-hint dns-mono dns-truncate" title={list.url}>{list.url}</p></div><div className="dns-preview-controls"><SelectControl label="规则动作" value={action} options={[{ value: "all", label: "全部" }, { value: "allow", label: T.dfPreviewFilterAllow }, { value: "block", label: T.dfPreviewFilterBlock }]} onValueChange={setAction} /><div className="dns-search"><input aria-label="搜索预览域名" placeholder={T.dfSearch} value={search} onChange={event => setSearch(event.target.value)} /><button type="button" aria-label="清空搜索" onClick={() => setSearch("")}><XMarkIcon /></button></div></div>
    {data && <p className="dns-hint">{data.source === "downloaded" ? T.dfPreviewDownloaded : T.dfPreviewUrl} · {query.search || query.action !== "all" ? `匹配 ${data.total} 条,共 ${data.count} 条` : `共 ${data.count} 条`}{data.unsupported > 0 && <Tooltip label={data.unsupportedExamples.join("\n")}><span className="dns-warning"> · {dnsMessage("dfSkipped", { n: data.unsupported })}</span></Tooltip>}</p>}
    <div className="dns-preview-list">{busy ? <div className="dns-empty"><span className="loading-spinner" />{T.dfLoading}</div> : error ? <p role="alert" className="dns-error">{error}</p> : !data?.rows.length ? <div className="dns-empty">没有匹配的条目</div> : data.rows.map((rule, index) => <div className="dns-preview-rule" key={index}><span className="dns-badge">{{ domain: "精确域名", domain_suffix: "域名后缀", domain_keyword: "域名关键词", domain_regex: "域名正则", ip_cidr: "IP CIDR" }[rule.type] || "其他"}</span><div className="dns-preview-value"><div className="dns-mono" title={rule.rule}>{rule.value}</div>{rule.conditional && <p className="dns-hint dns-mono">{rule.rule}</p>}</div><div className="dns-preview-actions"><span className={`dns-badge ${rule.action === "allow" ? "dns-success" : ""}`}>{rule.action === "allow" ? T.dfPreviewAllow : T.dfPreviewBlock}</span>{rule.important && <span className="dns-hint">important</span>}</div></div>)}</div>
    <DnsPagination total={data?.total || 0} page={data?.page || page} pageSize={data?.pageSize || size} busy={busy} onChange={(next, pageSize) => { setPage(next); setSize(pageSize); }} onToast={onToast} />
  </Modal>;
}
export function DnsFilterSettings({ status, busy, onSave, onApply, onToast }: { status: DnsFilterStatus; busy: boolean; onSave: (config: DnsFilterConfig) => Promise<boolean>; onApply: (update?: boolean, id?: string) => Promise<void>; onToast: (message: string) => void }) {
  const settings = status.settings, schedule = settings.autoUpdate || { enabled: false, days: 1, hour: 4 };
  const [editor, setEditor] = useState<DnsFilterList | null>(null), [preview, setPreview] = useState<DnsFilterList | null>(null), [deleting, setDeleting] = useState<DnsFilterList | null>(null), [expanded, setExpanded] = useState(false), [allow, setAllow] = useState(settings.allowDomains.join("\n"));
  const savedAllow = settings.allowDomains.join("\n");
  useEffect(() => { setAllow(savedAllow); }, [savedAllow]);
  useEffect(() => {
    const escape = (event: KeyboardEvent) => { if (event.key === "Escape" && !event.defaultPrevented && !document.querySelector('[data-slot="select-content"]') && !busy) { if (preview) setPreview(null); else { setEditor(null); setDeleting(null); } } };
    window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape);
  }, [busy, preview]);
  const save = (patch: Partial<DnsFilterConfig>) => onSave({ ...settings, ...patch });
  const saveEditor = async () => { if (!editor) return; const next = { ...editor, name: editor.name.trim(), url: editor.url.trim() }; if (await save({ lists: settings.lists.some(list => list.id === next.id) ? settings.lists.map(list => list.id === next.id ? next : list) : [...settings.lists, next] })) setEditor(null); };
  return <>
    <section className="surface dns-card"><header><div className="dns-title"><SwitchControl label="启用域名过滤" checked={settings.enabled} disabled={busy} onCheckedChange={enabled => void save({ enabled })} /><h2>{T.dfTitle}</h2><span className={`dns-badge ${status.pending ? "warning" : status.applied?.enabled ? "success" : ""}`}>{status.pending ? T.dfPending : status.applied?.enabled ? T.dfEnabled : T.dfDisabled}</span></div><div className="dns-actions"><IconButton label={T.dfUpdate} tooltip portalTooltip disabled={busy || !settings.lists.some(list => list.enabled)} onClick={() => void onApply(true)}><ArrowPathIcon /></IconButton><IconButton label={T.dfAdd} className="dns-add-button" aria-label="添加过滤名单" tooltip portalTooltip disabled={busy} onClick={() => setEditor({ id: `list-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`, name: "", url: "", enabled: true })}><PlusIcon /></IconButton></div></header><p className="dns-hint dns-description">{T.dfDescription}</p>
      {!settings.lists.length && <p className="dns-hint">{T.dfEmptyLists}</p>}{settings.lists.map(list => { const stats = status.lists[list.id]; return <div className="dns-filter-row" key={list.id}><SwitchControl label={`启用 ${list.name}`} checked={list.enabled} disabled={busy} onCheckedChange={enabled => void save({ lists: settings.lists.map(item => item.id === list.id ? { ...item, enabled } : item) })} /><div className="dns-filter-copy"><div className="dns-filter-meta"><strong>{list.name}</strong><span className="dns-mono dns-truncate" title={list.url}>{list.url}</span><span>{T.dfCount} {stats?.count === undefined ? "—" : stats.count.toLocaleString()}</span><span>{T.dfUpdated} {stats?.updatedAt ? new Date(stats.updatedAt).toLocaleString() : T.dfNotDownloaded}</span>{!!stats?.unsupported && <Tooltip label={stats.unsupportedExamples?.join("\n") || ""}><span className="dns-warning">{dnsMessage("dfSkipped", { n: stats.unsupported })}</span></Tooltip>}</div>{stats?.error && <p className="dns-error">{stats.error}</p>}</div><div className="dns-actions"><IconButton label={T.dfPreview} tooltip portalTooltip onClick={() => setPreview(list)}><EyeIcon /></IconButton><IconButton label={T.dfUpdateList} tooltip portalTooltip disabled={busy || !list.enabled} onClick={() => void onApply(true, list.id)}><ArrowPathIcon /></IconButton><IconButton label={T.dfEdit} tooltip portalTooltip disabled={busy} onClick={() => setEditor({ ...list })}><PencilSquareIcon /></IconButton><IconButton label={T.dfDelete} tooltip portalTooltip disabled={busy} onClick={() => setDeleting(list)}><TrashIcon /></IconButton></div></div>; })}
      <div className="dns-schedule"><SwitchControl label={T.dfAuto} checked={schedule.enabled} disabled={busy || !settings.enabled} onCheckedChange={enabled => void save({ autoUpdate: { ...schedule, enabled } })} /><span>{T.dfAuto}</span>{schedule.enabled && <><span>{T.dfAutoEvery}</span><SelectControl label="更新间隔" className="dns-schedule-select" value={String(schedule.days)} disabled={busy || !settings.enabled} options={[1, 3, 7, 14, 30].map(days => ({ value: String(days), label: dnsMessage("dfAutoDays", { days }) }))} onValueChange={days => void save({ autoUpdate: { ...schedule, days: Number(days) } })} /><span>{T.dfAutoAt}</span><SelectControl label="更新时间" className="dns-schedule-select" value={String(schedule.hour)} disabled={busy || !settings.enabled} options={Array.from({ length: 24 }, (_, hour) => ({ value: String(hour), label: `${String(hour).padStart(2, "0")}:00` }))} onValueChange={hour => void save({ autoUpdate: { ...schedule, hour: Number(hour) } })} /></>}<span className="dns-hint">{T.dfAutoHint}</span></div>
      <div className="dns-allow"><button type="button" className="dns-fold" aria-expanded={expanded} onClick={() => setExpanded(value => !value)}><ChevronDownIcon className={expanded ? "expanded" : ""} />{T.dfAllow} ({settings.allowDomains.length})</button>{expanded && <><p className="dns-hint">{T.dfAllowHint}</p><textarea aria-label={T.dfAllow} className="dns-mono" rows={3} placeholder="example.com\n*.example.com" value={allow} onChange={event => setAllow(event.target.value)} /><button type="button" className="compact-button" disabled={busy} onClick={() => void save({ allowDomains: parseAllowDomains(allow) })}>{T.dfSaveAllow}</button></>}</div>
    </section>
    {editor && !preview && <Modal title={T.dfEditList} className="dns-dialog routing-dialog" onClose={() => { if (!busy) setEditor(null); }} footer={<><button type="button" className="compact-button" disabled={busy} onClick={() => setEditor(null)}>取消</button><button form="dns-filter-list-form" type="submit" className="primary-button" disabled={busy}>保存</button></>}><form id="dns-filter-list-form" className="dns-form" onSubmit={event => { event.preventDefault(); void saveEditor(); }}><label className="dns-field"><span>{T.dfName}</span><input required maxLength={80} value={editor.name} disabled={busy} onChange={event => setEditor({ ...editor, name: event.target.value })} /></label><label className="dns-field"><span>{T.dfUrl}</span><div className="dns-search"><input required type="url" spellCheck={false} className="dns-mono" placeholder="https://example.com/filter.txt" maxLength={2048} value={editor.url} disabled={busy} onChange={event => setEditor({ ...editor, url: event.target.value })} /><IconButton label={T.dfPreview} tooltip portalTooltip disabled={!editor.url.trim()} onClick={() => setPreview(editor)}><EyeIcon /></IconButton></div></label></form></Modal>}
    {preview && <FilterPreview list={preview} onClose={() => setPreview(null)} onToast={onToast} />}
    {deleting && <Modal title={T.dfConfirmDelete} className="dns-dialog routing-dialog" onClose={() => { if (!busy) setDeleting(null); }} footer={<><button type="button" className="compact-button" disabled={busy} onClick={() => setDeleting(null)}>取消</button><button type="button" className="danger-button" disabled={busy} onClick={() => void save({ lists: settings.lists.filter(list => list.id !== deleting.id) }).then(success => { if (success) setDeleting(null); })}>删除</button></>}><strong>{deleting.name}</strong><p className="dns-hint dns-mono">{deleting.url}</p></Modal>}
  </>;
}
