import { useEffect, useRef, useState } from "react";
import { ArrowPathIcon, ChevronLeftIcon, ChevronRightIcon } from "@heroicons/react/24/outline";
import { api } from "../../api/client";
import type { DnsFilterStatus, DnsPageResult, DnsRecord } from "../../api/types";
import { IconButton } from "../../components/shared";
import { SelectControl } from "../../ui/controls";
import { DNS_TEXT as T } from "./DnsSettings.messages";
import { dnsError, dnsMessage } from "./DnsSettings.helpers";

export function DnsPagination({ total, page, pageSize, busy, onChange, onToast }: { total: number; page: number; pageSize: number; busy: boolean; onChange: (page: number, size: number) => void; onToast: (message: string) => void }) {
  const [custom, setCustom] = useState(false), [size, setSize] = useState(String(pageSize));
  const pages = Math.max(1, Math.ceil(total / pageSize));
  return <nav className="dns-pagination" aria-label="分页"><span>{dnsMessage("dfTotal", { n: total })}</span><div><SelectControl label="每页条数" className="dns-page-size" value={custom ? "custom" : String(pageSize)} disabled={busy} options={[10, 20, 50, 100, ...([10, 20, 50, 100].includes(pageSize) ? [] : [pageSize])].map(value => ({ value: String(value), label: `${value} 行 / 页` })).concat({ value: "custom", label: "自定义" })} onValueChange={value => { if (value === "custom") { setSize(String(pageSize)); setCustom(true); } else { setCustom(false); onChange(1, Number(value)); } }} />{custom && <><input aria-label="自定义每页条数" type="number" min={1} max={1000} value={size} onChange={event => setSize(event.target.value)} /><button type="button" className="compact-button" disabled={busy} onClick={() => { const next = Number(size); if (!Number.isInteger(next) || next < 1 || next > 1000) { onToast("每页条数填 1~1000 的整数"); return; } setCustom(false); onChange(1, next); }}>确认</button></>}<IconButton label={T.dfPrevious} tooltip portalTooltip disabled={busy || page <= 1} onClick={() => onChange(page - 1, pageSize)}><ChevronLeftIcon /></IconButton><span>{page} / {pages}</span><IconButton label={T.dfNext} tooltip portalTooltip disabled={busy || page >= pages} onClick={() => onChange(page + 1, pageSize)}><ChevronRightIcon /></IconButton></div></nav>;
}
export function DnsQueryRecords({ status, onToast }: { status: DnsFilterStatus; onToast: (message: string) => void }) {
  const [search, setSearch] = useState(() => new URLSearchParams(location.hash.split("?")[1] || "").get("dnsDomain") || ""), [query, setQuery] = useState(search), [result, setResult] = useState("blocked"), [request, setRequest] = useState({ page: 1, size: 10, revision: 0 }), [data, setData] = useState<DnsPageResult<DnsRecord>>({ rows: [], total: 0, page: 1, pageSize: 10 }), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const notify = useRef(onToast); notify.current = onToast;
  useEffect(() => { let active = true; setBusy(true); setError(""); void api.dnsRecords(query.trim(), result, request.page, request.size).then(next => { if (active) setData(next); }, reason => { if (active) { setError(dnsError(reason)); notify.current(dnsError(reason)); } }).finally(() => { if (active) setBusy(false); }); return () => { active = false; }; }, [query, result, request]);
  const refresh = () => { setQuery(search); setRequest(current => ({ ...current, page: 1, revision: current.revision + 1 })); };
  const resultLabel = (value: string) => ({ blocked: T.dfBlocked, allowed: T.dfAllowed, error: T.dfError, unknown: T.dfUnknown, policy: T.dfPolicy, cached: T.dfCached, local: T.dfLocal }[value] || value.toUpperCase());
  const sourceLabel = (row: DnsRecord) => row.source === "127.0.0.1" || row.source === "::1" ? row.via === "dnsmasq" ? T.dfRouterSelf : T.dfRouterSource : row.self ? `本机 ${row.self.kind.toUpperCase()} ${row.self.iface}` : row.name || "";
  return <section className="surface dns-card dns-records"><header><h2>{T.dfRecords}</h2><form className="dns-record-controls" onSubmit={event => { event.preventDefault(); refresh(); }}><input type="search" aria-label="搜索查询域名" placeholder={T.dfSearch} value={search} onChange={event => setSearch(event.target.value)} /><SelectControl label={T.dfResult} value={result} options={[{ value: "", label: T.dfAllResults }, { value: "blocked", label: T.dfBlocked }, { value: "allowed", label: T.dfAllowed }, { value: "dnsmasq", label: T.dfDnsmasqAnswered }, { value: "error", label: T.dfError }, { value: "unknown", label: T.dfUnknown }]} onValueChange={value => { setResult(value); setQuery(search); setRequest(current => ({ ...current, page: 1 })); }} /><IconButton label={T.dfQuery} tooltip portalTooltip disabled={busy} onClick={refresh}>{busy ? <span className="loading-spinner" /> : <ArrowPathIcon />}</IconButton></form></header>
    <p className="dns-hint">{T.dfRecordHint}</p>{status.queryLog?.reason === "user" && <p className="dns-warning">{T.dfQueryLogUser}</p>}{status.queryLog?.reason === "failed" && <p className="dns-warning">{T.dfQueryLogFailed}</p>}{!status.applied?.enabled ? <p className="dns-hint">{T.dfCollectDisabled}</p> : !status.connected && <p className="dns-warning">{T.dfDisconnected}</p>}{error && <p role="alert" className="dns-error">{error}</p>}
    <div className="dns-table-scroll"><table><thead><tr>{[T.dfTime, T.dfDomain, T.dfType, T.dfResult, T.dfSource, T.dfMatchedList, T.dfDuration].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{data.rows.map(row => <tr key={row.id}><td>{new Date(row.at).toLocaleString()}</td><td className="dns-record-domain dns-mono" title={row.domain}>{row.domain}</td><td>{row.qtype}</td><td><span className={`dns-badge ${row.result === "blocked" ? "error" : row.result === "allowed" ? "success" : row.result === "cached" || row.result === "local" ? "info" : ""}`}>{resultLabel(row.result)}</span></td><td>{row.source === "127.0.0.1" || row.source === "::1" ? sourceLabel(row) : <>{row.source || "—"}{sourceLabel(row) && <span className="dns-hint"> {sourceLabel(row)}</span>}</>}</td><td>{row.list || "—"}</td><td>{row.elapsed === null ? "—" : `${Math.round(row.elapsed)} ms`}</td></tr>)}{!data.rows.length && <tr><td colSpan={7} className="dns-empty">{busy ? T.dfLoading : T.dfNoRecords}</td></tr>}</tbody></table></div>
    <DnsPagination total={data.total} page={data.page} pageSize={data.pageSize} busy={busy} onChange={(page, size) => setRequest(current => ({ ...current, page, size }))} onToast={onToast} />
  </section>;
}
